# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'board_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiMainWindow(object):
    def setupUi(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.setEnabled(True)
        main_window.resize(1000, 700)
        main_window.setStyleSheet("background-color: rgb(255, 255, 255);\n")
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(219, 0, 781, 650))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\nborder:2px solid gray;\nborder-radius: 12px;")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 240, 61, 61))
        self.label.setToolTipDuration(-3)
        self.label.setStyleSheet("background-color: rgb(255, 0, 0);\nborder: 2px solid black;\nborder-radius:30px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/E:/Chrome_downlaod/red.png"))
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(10, 0, 201, 431))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border:2px solid gray;\nborder-radius:12px;")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(10, 440, 201, 211))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                    "border: 2px solid gray;\nborder-radius: 12px;")
        self.widget_3.setObjectName("widget_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 165, 51))
        self.pushButton.setStyleSheet("")
        self.pushButton.setIconSize(QtCore.QSize(17, 17))
        self.pushButton.setObjectName("pushButton")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ROLL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = UiMainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
